name: Compile LaTeX and HTML
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout cubical library
      uses: actions/checkout@v2
      with:
        repository: oisdk/cubical
        ref: combinatorics-paper-pin
        path: cubical
    
    - name: Put cubical library in Agda library list
      run: |
        echo "$GITHUB_WORKSPACE/cubical/cubical.agda-lib" > ~/.agda/libraries

    - uses: actions/cache@v2
      name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      id: cache-cabal
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}

    - name: Install cabal
      run: |
        apt-get update -y
        apt-get install -y cabal-install
        apt-get install -y libghc-zlib-dev libghc-zlib-bindings-dev

    - name: Install Agda
      if: steps.cache-cabal.outputs.cache-hit != 'true'
      run: |
        cabal update
        cabal install alex
        cabal install happy
        cabal install -v --ghc-options='+RTS -M2G -RTS' Agda-2.6.1
        export PATH='$HOME/.cabal/bin:$PATH'

    - name: Compile Agda HTML
      run: |
        cd "$GITHUB_WORKSPACE/main/agda"
        agda --html --html-dir=../docs README.agda

    # - name: Compile latex
    #   uses: dante-ev/latex-action@master
    #   with:
    #     root_file: paper.tex


