name: Compile LaTeX and HTML
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        ghc-ver: ["8.10.1"]
        cabal-ver: ["3.2"]
        cubical-commit: ["a01973ef7264f9454a40697313a2073c51a6b77a"]

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout cubical library
      uses: actions/checkout@v2
      with:
        repository: agda/cubical
        path: cubical

    - name: Put cubical library in Agda library list
      run: |
        mkdir -p ~/.agda/
        touch ~/.agda/libraries
        echo "$GITHUB_WORKSPACE/cubical/cubical.agda-lib" > ~/.agda/libraries
        
    - uses: actions/cache@v2
      name: Cache cubical compiles
      with:
        path: $GITHUB_WORKSPACE/cubical/_build
        key: ${{ runner.os }}-${{ matrix.cubical-commit }}

    - uses: actions/cache@v2
      name: Cache main compiles
      with:
        path: $GITHUB_WORKSPACE/main/_build
        key: ${{ runner.os }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      id: cache-cabal
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          ~/.cabal/bin
          dist-newstyle
        key: ${{ runner.os }}

    - name: Install cabal
      uses: actions/setup-haskell@v1.1
      with:
        ghc-version: matrix.ghc-ver
        cabal-version: matrix.cabal-ver

    - name: Put cabal programs in PATH
      run: echo "::add-path::~/.cabal/bin"

    - name: Install Agda
      if: steps.cache-cabal.outputs.cache-hit != 'true'
      run: |
        cabal update
        cabal install --overwrite-policy=always --ghc-options='-O0 +RTS -M6G -RTS' alex-3.2.5
        cabal install --overwrite-policy=always --ghc-options='-O0 +RTS -M6G -RTS' happy-1.19.12
        cabal install --overwrite-policy=always --ghc-options='-O0 +RTS -M6G -RTS' Agda-2.6.1

    - name: Compile all literate agda
      run: |
        sudo apt-get install texlive-binaries
        cd main
        rm .latexmkrc
        cd agda
        find . -type f -name '*.lagda' | while read -r code ; do
            agda --latex --latex-dir=. $code
        done

    - name: Compile latex
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: main
        root_file: paper.tex

    - name: Upload generated pdf
      uses: actions/upload-artifact@v2
      with:
        name: paper
        path: main/paper.pdf

    - name: Compile Agda HTML
      run: |
        cd "$GITHUB_WORKSPACE/main/agda"
        agda --html --html-dir=../docs README.agda

    - name: Move generated pdf in with html
      run: mv main/paper.pdf main/docs/paper.pdf

    - name: Deploy html and pdf to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: main/docs
