name: Compile LaTeX and HTML
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        path: main

    - name: Install cabal
      uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.8'
        cabal-version: '3.0.0.0'

    - name: Install Agda
      if: steps.cache-cabal.outputs.cache-hit != 'true'
      run: |
        cabal update
        cabal install alex
        cabal install happy
        cabal install -v --ghc-options='+RTS -M2G -RTS' Agda-2.6.1
        export PATH='$HOME/.cabal/bin:$PATH'

    - name: Checkout cubical library
      uses: actions/checkout@v2
      with:
        repository: oisdk/cubical
        ref: combinatorics-paper-pin
        path: cubical
    
    - name: Put cubical library in Agda library list
      run: |
        echo "$GITHUB_WORKSPACE/cubical/cubical.agda-lib" > ~/.agda/libraries

    - name: Compile Agda HTML
      run: |
        cd "$GITHUB_WORKSPACE/main/agda"
        agda --html --html-dir=../docs README.agda

    # - name: Compile latex
    #   uses: dante-ev/latex-action@master
    #   with:
    #     root_file: paper.tex


